#automation platform-> 1) build 2)unit tests test 3) static code analysis (linting) 4) deploy
#workflow is sequence of activities, is a YAML file which will be parse by github actions
name: ci-workflow
on: 
  push: 
jobs: #real objective of workflow, every job will be running on different runner, can run parallel or sequence, dependencies matters. 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: welcome steps
        run: echo "Welcome to yhe Github Actions"   #run tells its a shell command
      - name: Clone Repo  #jobs and repo working on seperate cloud, job need to clone it to access it
        uses: actions/checkout@v4 
      - name: Repository Information
        run: | #expressin syntax -> ${{github.repository}}, expression will always produce value based upon some operation, action engine will evaluate it | github.repository-> context
          echo "Follwoing is the information abput cloned Repo"
          echo "Repository Name : ${{github.repository}} "            
          echo "Repository Owner : ${{github.owner}} "
          git branch 
          git log
          got config --local --list 
# this all command will be sen to runner where git already install
    
  